### ISSUE TITLE
dispatch.prepare is not a function

### ISSUE THREAD

**Issue by raj-vaja** [flowplayer/react-native-sdk-demo#2]
![Screenshot_4](https://github.com/flowplayer/react-native-sdk-demo/assets/110589076/5a05aa0d-9f96-467d-9357-f42498d354b0)
I ran this repo in local, got an error dispatch.prepare is not a function

![Screenshot_5](https://github.com/flowplayer/react-native-sdk-demo/assets/110589076/c687c5d1-ed24-4b17-88ef-a7294b8a4e92)
After reloading the app, got an error lateinit property player had not been initialized

here is a code ss
![Screenshot_6](https://github.com/flowplayer/react-native-sdk-demo/assets/110589076/56668c60-ce52-4522-887e-4319de03f8c2)

**Comment by br3akzero** [comment]
Hey @neha-359 what version of the SDK are you using and please optionally access the prepare method like this:

`dispatch?.prepare?.(VIDEO)`

**Comment by raj-vaja** [comment]
I am using ^1.0.0-rc.1 this version

**Comment by br3akzero** [comment]
@neha-359 please use `1.0.0` and also implement the code as demonstrated above. I will close this issue as this issue was tied to old version of the SDK. If you encounter any other issue please create a new issue or contact our support.
